<%@ Page Title="" Language="C#" MasterPageFile="~/HeadAndFooter.Master" AutoEventWireup="true" CodeBehind="PrivacyPolicyPage.aspx.cs" Inherits="TheArtling.CustomerCare.PrivacyPolicyPage" %>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <style>
        @font-face {
            font-family: Arvo-Regular;
            src: url(Arvo-Regular.ttf);
            font-family: Arvo-Bold;
            src: url(Arvo-Bold.ttf);
        }

        .content-wrapper {
            width: 100%;
            margin-bottom: 10%;
            margin-left: 20%;
            max-width: 60%;
        }

        .content {
            width: 100%;
            text-align: left;
        }

        .title-text {
            font-family: Arvo-Bold;
            font-size: 30px;
            font-weight: 800;
        }

        .content-title {
            font-family: Arvo-Regular;
            font-size: 21px;
            font-weight: 600;
        }

        .content-text {
            font-family: Arvo-Regular;
            font-size: 18px;
            font-weight: 400;
        }

        .small-square {
            border: 1px solid black;
            height: 5px;
            width: 5px;
            float: left;
            margin-top: 6px;
        }

        .small-circle {
            display: inline-block;
            border-radius: 50%;
            height: 5px;
            width: 5px;
            float: left;
            margin-top: 6px;
            margin-left: 5%;
            background-color: black;
        }
    </style>
    <div class="content-wrapper">
        <div class="title-text" style="text-align: center;">Privacy Policy</div>
        <br />
        <div class="content">
            <div class="content-text">The Artling Pte Ltd ("us", "we", or "our") operates the https://theartling.com/ website, the https://projects.theartling.com website and the The Artling mobile application (the "Service").</div>
            <br />
            <div class="content-text">This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data.</div>
            <br />
            <div class="content-text">We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.</div>
            <br />
            <div class="content-title">DEFINITIONS</div>
            <br />
            <div class="content-title">Service</div>
            <div class="content-text">Service means the https://theartling.com/en/ website, the https://projects.theartling.com website and the The Artling mobile application operated by The Artling Pte Ltd</div>
            <br />
            <div class="content-title">Personal Data</div>
            <div class="content-text">Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</div>
            <br />
            <div class="content-title">Usage Data</div>
            <div class="content-text">Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</div>
            <br />
            <div class="content-title">Cookies</div>
            <div class="content-text">Cookies are small pieces of data stored on your device (computer or mobile device).</div>
            <br />
            <div class="content-text">Data Controller</div>
            <div class="content-text">Data Controller means the natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal information are, or are to be, processed.</div>
            <br />
            <div class="content-text">For the purpose of this Privacy Policy, we are a Data Controller of your Personal Data.</div>
            <br />
            <div class="content-title">Data Processors (or Service Providers)</div>
            <div class="content-text">Data Processor (or Service Provider) means any natural or legal person who processes the data on behalf of the Data Controller.</div>
            <br />
            <div class="content-text">We may use the services of various Service Providers in order to process your data more effectively.</div>
            <br />
            <div class="content-title">Data Subject (or User)</div>
            <div class="content-text">Data Subject is any living individual who is using our Service and is the subject of Personal Data.</div>
            <br />
            <div class="content-title">INFORMATION COLLECTION AND USE</div>
            <div class="content-text">We collect several different types of information for various purposes to provide and improve our Service to you.</div>
            <br />
            <div class="content-title">Types of Data Collected</div>
            <br />
            <div class="content-title">Personal Data</div>
            <br />
            <div class="content-text">While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:</div>
            <br />
            <span class="small-circle"></span>
            <div class="content-text" style="float: left;">Email address</div>
            <br />
            <br />
            <span class="small-circle"></span>
            <div class="content-text" style="float: left;">First name and last name</div>
            <br />
            <br />
            <span class="small-circle"></span>
            <div class="content-text" style="float: left;">Phone number</div>
            <br />
            <br />
            <span class="small-circle"></span>
            <div class="content-text" style="float: left;">Address, State, Province, ZIP/Postal code, City</div>
            <br />
            <br />
            <span class="small-circle"></span>
            <div class="content-text" style="float: left;">Cookies and Usage Data</div>
            <br />
            <br />
            <div class="content-text">We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or instructions provided in any email we send.</div>
            <br />
            <div class="content-title">Usage Data</div>
            <br />
            <br />

            <div class="content-text">We may also collect information that your browser sends whenever you visit our Service or when you access the Service by or through a mobile device ("Usage Data").</div>
            <br />
            <br />
            <div class="content-text">This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</div>
            <br />
            <br />
            <div class="content-text">When you access the Service by or through a mobile device, this Usage Data may include information such as the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data.</div>
            <br />
            <br />
            <div class="content-title">Tracking Cookies Data</div>
            <br />
            <br />
            <div class="content-text">
                We use cookies and similar tracking technologies to track the activity on our Service and hold certain information.
                <br />
                <br />
                Cookies are files with small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Tracking technologies also used are beacons, tags, and scripts to collect and track information and to improve and analyze our Service.
                <br />
                <br />
                You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.
                <br />
                <br />
                Here is a list of cookies that we use. We’ve listed them here so you that you can choose if you want to opt-out of cookies or not.
                <br />
                <br />
                <span class="small-circle"></span>
                <div style="float: left;">__zlcmid, unique token, sessional, used for the live chat widget provided by https://www.zopim.com/ </div>
                <br />
                <br />
                <span class="small-circle"></span>
                <div style="float: left;">csrftoken, unique token, sessional, used to secure form submits. https://docs.djangoproject.com/en/dev/ref/csrf/ </div>
                <br />
                <br />
                <span class="small-circle"></span>
                <div style="float: left;">messages, html, sessional, used to display user-action related notifications (e.g. "You have been logged out.") </div>
                <br />
                <br />
                <span class="small-circle"></span>
                <div style="float: left;">sessionid, unique token, sessional, used to identify the current user</div>
            </div>
            <br />
            <br />
            <div class="content-title">USE OF DATA</div>
            <br />
            <br />
            <div class="content-text">
                <span class="small-circle"></span>
                <div style="float: left;">The Artling Pte Ltd uses the collected data for various purposes:</div>
                <br />
                <br />
                <span class="small-circle"></span>
                <div style="float: left;">To provide and maintain our Service</div>
                <br />
                <br />
                <span class="small-circle"></span>
                <div style="float: left;">To notify you about changes to our Service</div>
                <br />
                <br />
                <span class="small-circle"></span>
                <div style="float: left;">To allow you to participate in interactive features of our Service when you choose to do so</div>
                <br />
                <br />
                <span class="small-circle"></span>
                <div style="float: left;">To provide customer support</div>
                <br />
                <br />
                <span class="small-circle"></span>
                <div style="float: left;">To gather analysis or valuable information so that we can improve our Service</div>
                <br />
                <br />
                <span class="small-circle"></span>
                <div style="float: left;">To monitor the usage of our Service</div>
                <br />
                <br />
                <span class="small-circle"></span>
                <div style="float: left;">To detect, prevent and address technical issues</div>
                <br />
                <br />
                <span class="small-circle"></span>
                <div style="float: left;">To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information</div>
            </div>
            <br />
            <div class="content-title">Legal Basis for Processing Personal Data Under General Data Protection Regulation (GDPR)</div>
            <br />
            <div class="content-text">
                <span class="small-circle"></span>
                <div style="float: left;">If you are from the European Economic Area (EEA), The Artling Pte Ltd legal basis for collecting and using the personal information described in this Privacy Policy depends on the Personal Data we collect and the specific context in which we collect it.</div>
                <br />
                <br />
                <span class="small-circle"></span>
                <div style="float: left;">The Artling Pte Ltd may process your Personal Data because:</div>
                <br />
                <br />
                <span class="small-circle"></span>
                <div style="float: left;">We need to perform a contract with you</div>
                <br />
                <br />
                <span class="small-circle"></span>
                <div style="float: left;">You have given us permission to do so</div>
                <br />
                <br />
                <span class="small-circle"></span>
                <div style="float: left;">The processing is in our legitimate interests and it's not overridden by your rights</div>
                <br />
                <br />
                <span class="small-circle"></span>
                <div style="float: left;">For payment processing purposes</div>
                <br />
                <br />
                <span class="small-circle"></span>
                <div style="float: left;">To comply with the law</div>
            </div>
            <br />
            <br />
            <div class="content-title">RETENTION OF DATA</div>
            <br />
            <div class="content-text">The Artling Pte Ltd will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</div>
            <br />
            <br />
            <div class="content-text">The Artling Pte Ltd will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.</div>
            <br />
            <br />
            <div class="content-title">TRANSFER OF DATA</div>
            <br />
            <div class="content-text">Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction.</div>
            <br />
            <br />
            <div class="content-text">If you are located outside Singapore and choose to provide information to us, please note that we transfer the data, including Personal Data, to Singapore and process it there.</div>
            <br />
            <br />
            <div class="content-text">Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</div>
            <br />
            <br />
            <div class="content-text">The Artling Pte Ltd will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.</div>
            <br />
            <br />
            <div class="content-title">DISCLOSURE OF DATA</div>
            <br />
            <div class="content-title">Business Transaction</div>
            <br />
            <div class="content-text">If The Artling Pte Ltd is involved in a merger, acquisition or asset sale, your Personal Data may be transferred. We will provide notice before your Personal Data is transferred and becomes subject to a different Privacy Policy.</div>
            <br />
            <div class="content-title">Disclosure for Law Enforcement</div>
            <br />
            <div class="content-text">Under certain circumstances, The Artling Pte Ltd may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</div>
            <br />
            <div class="content-title">Legal Requirements</div>
            <br />
            <div class="content-text">
                <span class="small-circle"></span>
                <div style="float: left;">The Artling Pte Ltd may disclose your Personal Data in the good faith belief that such action is necessary to:</div>
                <br />
                <br />
                <span class="small-circle"></span>
                <div style="float: left;">To comply with a legal obligation</div>
                <br />
                <br />
                <span class="small-circle"></span>
                <div style="float: left;">To protect and defend the rights or property of The Artling Pte Ltd</div>
                <br />
                <br />
                <span class="small-circle"></span>
                <div style="float: left;">To prevent or investigate possible wrongdoing in connection with the Service</div>
                <br />
                <br />
                <span class="small-circle"></span>
                <div style="float: left;">To protect the personal safety of users of the Service or the public</div>
                <br />
                <br />
                <span class="small-circle"></span>
                <div style="float: left;">To protect against legal liability</div>
            </div>
            <br />
            <br />
            <div class="content-title">SECURITY OF DATA</div>
            <br />
            <div class="content-text">To protect your personal information, we take reasonable precautions and follow industry best practices to make sure it is not inappropriately lost, misused, accessed, disclosed, altered or destroyed.</div>
            <br />
            <br />
            <div class="content-text">If you provide us with your credit card information, the information is encrypted using secure socket layer technology (SSL). Although no method of transmission over the Internet or electronic storage is 100% secure, we follow all necessary requirements and implement additional generally accepted industry standards.</div>
            <br />
            <br />
            <div class="content-title">Your Data Protection Rights Under General Data Protection Regulation (GDPR)</div>
            <br />
            <div class="content-text">
                If you are a resident of the European Economic Area (EEA), you have certain data protection rights. The Artling Pte Ltd aims to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.
                <br />
                <br />
                If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please contact us.
                <br />
                <br />
                In certain circumstances, you have the following data protection rights:
                <br />
                <br />
                <span style="font-weight: bold;">The right to access</span>, update or to delete the information we have on you. Whenever made possible, you can access, update or request deletion of your Personal Data directly within your account settings section. If you are unable to perform these actions yourself, please contact us to assist you.
                <br />
                <br />
                <span style="font-weight: bold;">The right of rectification</span>. You have the right to have your information rectified if that information is inaccurate or incomplete.
                <br />
                <br />
                <span style="font-weight: bold;">The right to object</span>. You have the right to object to our processing of your Personal Data.
                <br />
                <br />
                <span style="font-weight: bold;">The right of restriction</span>. You have the right to request that we restrict the processing of your personal information.
                <br />
                <br />
                <span style="font-weight: bold;">The right to data portability</span>. You have the right to be provided with a copy of the information we have on you in a structured, machine-readable and commonly used format.
                <br />
                <br />
                <span style="font-weight: bold;">The right to withdraw consent</span>. You also have the right to withdraw your consent at any time where The Artling Pte Ltd relied on your consent to process your personal information.
                <br />
                <br />
                Please note that we may ask you to verify your identity before responding to such requests.
                <br />
                <br />
                You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).
            </div>
            <br />
            <br />
            <div class="content-title">SERVICE PROVIDERS</div>
            <br />
            <div class="content-text">We may employ third party companies and individuals to facilitate our Service ("Service Providers"), to provide the Service on our behalf, to perform Service-related services or to assist us in analyzing how our Service is used.</div>
            <br />
            <div class="content-text">These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</div>
            <br />
            <div class="content-title">Analytics</div>
            <br />
            <div class="content-text">We may use third-party Service Providers to monitor and analyze the use of our Service.</div>
            <br />
            <div class="content-title">
                Google Analytics<div class="content-text">
                    <div class="content-text">Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualize and personalize the ads of its own advertising network.</div>
                    <br />
                    <div class="content-text">For more information on the privacy practices of Google, please visit the Google Privacy Terms web page: http://www.google.com/intl/en/policies/privacy/ </div>
                    <br />
                    <div class="content-title">Payments</div>
                    <br />
                    <div class="content-text">
                        We may provide paid products and/or services within the Service. In that case, we use third-party services for payment processing (e.g. payment processors).
                    <br />
                        <br />
                        We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.
                    <br />
                        <br />
                        The payment processors we work with are:
                    <br />
                        <br />
                        <span style="font-weight: bold;">Stripe</span>
                        <br />
                        <br />
                        Their Privacy Policy can be viewed at https://stripe.com/us/privacy
                    </div>
                    <br />
                    <div class="content-title">LINKS TO OTHER SITES</div>
                    <br />
                    <div class="content-text">
                        Our Service may contain links to other sites that are not operated by us. If you click on a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.
                   <br />
                        <br />
                        We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
                    </div>
                    <br />
                    <div class="content-title">AGE OF CONSENT</div>
                    <br />
                    <div class="content-text">By using this site, you represent that you are at least the age of majority in your country/state or province of residence, or that you are the age of majority in your country/state or province of residence and you have given us your consent to allow any of your minor dependents to use this site.</div>
                    <br />
                    <div class="content-title">CHANGES TO THIS PRIVACY POLICY</div>
                    <div class="content-text">
                        We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.
                    <br />
                        <br />
                        We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the "effective date" at the top of this Privacy Policy.
                    <br />
                        <br />
                        You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
                    </div>
                    <br />
                    <div class="content-title">CONTACT US</div>
                    <br />
                    <div class="content-text">
                        If you would like to: access, correct, amend or delete any personal information we have about you, register a complaint, or simply want more information contact our Privacy Compliance Officer at admin@theartling.com or by mail at The Artling Pte Ltd:
                        <br />
                        [Re: Privacy Compliance Officer]
                        <br />
                        [91B Tanjong Pagar Road, Singapore 088512]
                    </div>
                    <br />
                </div>
            </div>
        </div>
    </div>
</asp:Content>
