//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheArtling.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int CartId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string UserId { get; set; }
        public Nullable<short> Quantity { get; set; }
        public string OrderId { get; set; }
        public Nullable<decimal> TPrice { get; set; }
    
        public virtual User User { get; set; }
    }
}
