//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheArtling.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favourite
    {
        public Favourite()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int FId { get; set; }
        public string userId { get; set; }
        public Nullable<int> ProductId { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
