//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheArtling.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public string ProductImage { get; set; }
        public Nullable<System.DateTime> FinishedYear { get; set; }
        public Nullable<int> ProductLength { get; set; }
        public Nullable<int> ProductWidth { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> ArtistId { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Status { get; set; }
        public int ArtistArtistId { get; set; }
        public int FavouriteFId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Artist Artist { get; set; }
        public virtual OrderDetail OrderDetail { get; set; }
        public virtual Favourite Favourite { get; set; }
    }
}
