//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheArtling.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingDetail
    {
        public int ShippingDetailsId { get; set; }
        public string Name { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public Nullable<int> Poscode { get; set; }
        public string PhoneNumber { get; set; }
        public string UserId { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
